[package]
name = "dns-update"
version = "0.0.1"
publish = false
edition = "2024"

[dependencies.cloudflare]
version = "0.14.0"
default-features = false
features = ["blocking", "default-tls"]

[dependencies]
serde = "1.0.228"
toml = "0.9.8"
